const keyMirror = require("key-mirror");

module.exports = {
  ...keyMirror({
    COMPANIES_LIST_DID_MOUNT: null,
    COMPANIES_LIST_FETCH: null,
    COMPANIES_LIST_SUCCESS: null,
    COMPANIES_LIST_ERROR: null,
    COMPANIES_LIST_DONE: null,

    AGENCIES_LIST_DID_MOUNT: null,
    AGENCIES_LIST_FETCH: null,
    AGENCIES_LIST_SUCCESS: null,
    AGENCIES_LIST_ERROR: null,
    AGENCIES_LIST_DONE: null,

    COMPANIES_TEST_MANAGER_LIST_DID_MOUNT: null,
    COMPANIES_TEST_MANAGER_LIST_FETCH: null,
    COMPANIES_TEST_MANAGER_LIST_SUCCESS: null,
    COMPANIES_TEST_MANAGER_LIST_ERROR: null,
    COMPANIES_TEST_MANAGER_LIST_DONE: null,

    AGENCIES_TEST_MANAGER_LIST_DID_MOUNT: null,
    AGENCIES_TEST_MANAGER_LIST_FETCH: null,
    AGENCIES_TEST_MANAGER_LIST_SUCCESS: null,
    AGENCIES_TEST_MANAGER_LIST_ERROR: null,
    AGENCIES_TEST_MANAGER_LIST_DONE: null,

    COMPANIES_USERS_LIST_DID_MOUNT: null,
    COMPANIES_USERS_LIST_FETCH: null,
    COMPANIES_USERS_LIST_SUCCESS: null,
    COMPANIES_USERS_LIST_ERROR: null,
    COMPANIES_USERS_LIST_DONE: null,
  })
};
