export const COMPANIES_LIST_DID_MOUNT = 'COMPANIES_LIST_DID_MOUNT';
export const COMPANIES_LIST_FETCH = 'COMPANIES_LIST_FETCH';
export const COMPANIES_LIST_SUCCESS = 'COMPANIES_LIST_SUCCESS';
export const COMPANIES_LIST_ERROR = 'COMPANIES_LIST_ERROR';
export const COMPANIES_LIST_DONE = 'COMPANIES_LIST_DONE';

export const AGENCIES_LIST_DID_MOUNT = 'AGENCIES_LIST_DID_MOUNT';
export const AGENCIES_LIST_FETCH = 'AGENCIES_LIST_FETCH';
export const AGENCIES_LIST_SUCCESS = 'AGENCIES_LIST_SUCCESS';
export const AGENCIES_LIST_ERROR = 'AGENCIES_LIST_ERROR';
export const AGENCIES_LIST_DONE = 'AGENCIES_LIST_DONE';

export const COMPANIES_TEST_MANAGER_LIST_DID_MOUNT = 'COMPANIES_TEST_MANAGER_LIST_DID_MOUNT';
export const COMPANIES_TEST_MANAGER_LIST_FETCH = 'COMPANIES_TEST_MANAGER_LIST_FETCH';
export const COMPANIES_TEST_MANAGER_LIST_SUCCESS = 'COMPANIES_TEST_MANAGER_LIST_SUCCESS';
export const COMPANIES_TEST_MANAGER_LIST_ERROR = 'COMPANIES_TEST_MANAGER_LIST_ERROR';
export const COMPANIES_TEST_MANAGER_LIST_DONE = 'COMPANIES_TEST_MANAGER_LIST_DONE';
