export const COMPANIES_LIST_DID_MOUNT = 'COMPANIES_LIST_DID_MOUNT';
export const COMPANIES_LIST_FETCH = 'COMPANIES_LIST_FETCH';
export const COMPANIES_LIST_SUCCESS = 'COMPANIES_LIST_SUCCESS';
export const COMPANIES_LIST_ERROR = 'COMPANIES_LIST_ERROR';
export const COMPANIES_LIST_DONE = 'COMPANIES_LIST_DONE';
